Test/tip factory
sergey-oreshkin/tipster-server pull request #18
Opened 2022-12-23 12:57 UTC by aBoyarov

2022-12-26 12:15 UTC, sergey-oreshkin requested changes

2022-12-26 12:15 UTC, sergey-oreshkin commented on src/test/java/com/home/tipster/tips/factory/TipFactoryTest.java
> +
Optional.ofNullable надо писать там где если параметр null, то пустой опшионал получится
тут то он вроде никак не должен быть null, поэтому лучше Optional.of использовать

2022-12-26 13:24 UTC, aBoyarov commented on src/test/java/com/home/tipster/tips/factory/TipFactoryTest.java
> +
Сделал

2022-12-27 04:14 UTC, sergey-oreshkin approved these changes

2022-12-27 04:16 UTC, merged