Test/theme factory
sergey-oreshkin/tipster-server pull request #19
Opened 2022-12-23 13:32 UTC by aBoyarov

2022-12-26 12:17 UTC, sergey-oreshkin requested changes

2022-12-26 12:17 UTC, sergey-oreshkin commented on src/test/java/com/home/tipster/themes/factory/ThemesFactoryTest.java
> +
в TipFactoryTest писал это в одну строку, тут перенос
и опшионал оф тоже лучше

2022-12-26 13:21 UTC, aBoyarov commented on src/test/java/com/home/tipster/themes/factory/ThemesFactoryTest.java
> +
Лучше было бы всё сделать в таком формате, но легче исправить в одном месте одной ветки, поэтому сделал в одну строку, заменил на OF

2022-12-27 04:15 UTC, sergey-oreshkin approved these changes

2022-12-27 04:15 UTC, merged