test
sergey-oreshkin/tipster-server pull request #3
Opened 2022-11-14 15:17 UTC by IrinaSlipchenko

2022-11-20 09:54 UTC, sergey-oreshkin requested changes
нужно кое что поправить

2022-11-20 09:54 UTC, sergey-oreshkin commented on pom.xml
>  		<dependency>
где-то есть пустые строки между зависимостями. где то нет, не понятно по какому принципу.
может быть лучше вообще без пустых строк или сделать их везде. или отделять пустыми строками только целые разделы типа <parent>, <properties>, <dependencies>.
также внутри <dependencies> неплохо было бы сгруппировать зависимости - типа спринговые вместе, базы данных вместе, все прочие в конце

2022-11-20 09:54 UTC, sergey-oreshkin commented on src/main/resources/application.yml
> +    password: password     # пароль консоли
база создает файл в корне проекта, это файл может ненароком улететь в репозиторий, так что лучше добавить его в .gitignore явно, чтоб не приходилось помнить о нем постоянно..

2022-11-20 09:54 UTC, sergey-oreshkin commented on src/main/resources/db/changelog/changeset/create-tips-table.yaml
> +                  type: varchar(2000)
думаю не стоит ограничивать сам текст, тем более 2000 не так уж и много. может быть тут стоит использовать тип text

2022-11-20 19:23 UTC, IrinaSlipchenko commented on pom.xml
>  		<dependency>
исправлено

2022-11-20 19:31 UTC, IrinaSlipchenko commented on src/main/resources/db/changelog/changeset/create-tips-table.yaml
> +                  type: varchar(2000)
ok

2022-11-20 19:31 UTC, IrinaSlipchenko commented on src/main/resources/application.yml
> +    password: password     # пароль консоли
ok

2022-11-21 05:01 UTC, sergey-oreshkin approved these changes

2022-11-21 05:01 UTC, merged