Add tips
sergey-oreshkin/tipster-server pull request #5
Opened 2022-11-23 14:35 UTC by aBoyarov

2022-11-24 05:09 UTC, sergey-oreshkin requested changes

2022-11-24 05:09 UTC, sergey-oreshkin commented on src/main/java/com/home/tipster/tips/service/TipsServiceImpl.java
> +        tips.setCreate(LocalDateTime.now());
можно сделать аннотацией хибернейта, выше писал

2022-11-24 05:09 UTC, sergey-oreshkin commented on src/main/java/com/home/tipster/tips/service/TipsServiceImpl.java
> +    }
нужно валидировать тему перед сохранением, иначе можно тут словить ошибку

2022-11-24 05:09 UTC, sergey-oreshkin commented on src/main/java/com/home/tipster/tips/service/TipsServiceImpl.java
> +        Tips oldTips = tipsRepository.findById(tips.getId()).orElseThrow();
строки 32, 33 делают одно и то же. лучше в приватном методе валидировать тему, эта валидация нужна в 3-х методах уже.

2022-11-24 05:09 UTC, sergey-oreshkin commented on src/main/java/com/home/tipster/tips/service/TipsServiceImpl.java
> +        oldTips.setUpdate(LocalDateTime.now());
тоже можно аннотацией делать

2022-11-24 05:09 UTC, sergey-oreshkin commented on src/main/java/com/home/tipster/tips/repository/TipsRepository.java
> +    List<Tips> finaAllByThemesId(@Param("themeId") Long themeId);
только если поле переименуешь в theme, тут тоже исправь на finaAllByThemeId(Long themeId)

2022-11-24 05:19 UTC, sergey-oreshkin commented on src/main/java/com/home/tipster/tips/model/TipsDto.java
> +    private String text;
так же заголовок и текст не должны быть пустыми. надо добавить в миграцию nullable false для заголовка, че то посмотрел там нет этого

2022-11-25 04:05 UTC, aBoyarov commented on src/main/java/com/home/tipster/tips/controller/TipsController.java
> +        log.info("Creates tips with title{}", tipsDto.getTitle());
Сделал

2022-11-25 04:05 UTC, aBoyarov commented on src/main/java/com/home/tipster/tips/controller/TipsController.java
> +        log.info("Updates tips with id{}", tipsDto.getId());
Тут тоже

2022-11-25 04:05 UTC, aBoyarov commented on src/main/java/com/home/tipster/tips/model/Tips.java
> +public class Tips {
И тут

2022-11-25 04:05 UTC, aBoyarov commented on src/main/java/com/home/tipster/tips/model/Tips.java
> +
Добавил

2022-11-25 04:05 UTC, aBoyarov commented on src/main/java/com/home/tipster/tips/model/Tips.java
> +
И это тоже

2022-11-25 04:05 UTC, aBoyarov commented on src/main/java/com/home/tipster/tips/model/Tips.java
> +
Переименовал

2022-11-25 04:08 UTC, aBoyarov commented on src/main/java/com/home/tipster/tips/model/TipsDto.java
> +    private String text;
Добавил ограничение на заголовок @Size(max = 100), и на оба поля @NotNull и добавил аннотацию @Valid в контроллер, в эндпоинтах create и update, только не совсем понимаю как апдейтить объект если захочется изменить только одно из полей

2022-11-25 04:10 UTC, aBoyarov commented on src/main/java/com/home/tipster/tips/repository/TipsRepository.java
> +    List<Tips> finaAllByThemesId(@Param("themeId") Long themeId);
Иде с тобой не согласится, сама подсказала метод с таким названием findByThemeId, но я на всякий случай закомментировал старый код

2022-11-25 04:10 UTC, aBoyarov commented on src/main/java/com/home/tipster/tips/service/TipsServiceImpl.java
> +        tips.setCreate(LocalDateTime.now());
Убрал

2022-11-25 04:13 UTC, aBoyarov commented on src/main/java/com/home/tipster/tips/service/TipsServiceImpl.java
> +    }
Добавил проверку по айдишнику, существует ли такая тема в базе

2022-11-25 04:14 UTC, aBoyarov commented on src/main/java/com/home/tipster/tips/service/TipsServiceImpl.java
> +        oldTips.setUpdate(LocalDateTime.now());
Если ты про @UpdateTimestamp то добавил

2022-11-25 04:37 UTC, aBoyarov commented on src/main/java/com/home/tipster/tips/service/TipsServiceImpl.java
> +        Tips oldTips = tipsRepository.findById(tips.getId()).orElseThrow();
Сделал методы валидации по айди темы и типа, но конструкция Tip oldTip = validTipId(tip.getId()) меня смущает, мне кажется лучше сделать валидацию по айди в методах getId для темы и типа и каждый раз когда нужна проверка существования в базе вызывать этот метод и заодно получать значение если оно есть, это внесёт ясность в код, но пока оставлю как есть

2022-11-25 04:41 UTC, sergey-oreshkin commented on src/main/java/com/home/tipster/tips/repository/TipsRepository.java
> +    List<Tips> finaAllByThemesId(@Param("themeId") Long themeId);
Вроде если нужен список надо начинать c findAll.. Мало ли что идея говорит, нашёл кого слушатт

2022-11-25 04:44 UTC, sergey-oreshkin commented on src/main/java/com/home/tipster/tips/service/TipsServiceImpl.java
> +        Tips oldTips = tipsRepository.findById(tips.getId()).orElseThrow();
Там вроде есть классы для маппера типа ThemeFactory. Может быть их использовать для этого?

2022-11-25 04:47 UTC, sergey-oreshkin commented on src/main/java/com/home/tipster/tips/service/TipsServiceImpl.java
> +        Tips oldTips = tipsRepository.findById(tips.getId()).orElseThrow();
Ну и метод можно назвать как то типа getOrThrow который по айди чо то возвращает

2022-11-26 10:17 UTC, sergey-oreshkin requested changes

2022-11-26 10:17 UTC, sergey-oreshkin commented on src/main/java/com/home/tipster/tips/model/Tip.java
> +@ToString
@ToString в Entity лучше не писать без особой необходимости, он может вызвать лишние запросы в БД или вообще переполнение стека если в Entity вдруг добавят какую то подколлекцию и там случится кольцевая зависимость

2022-11-26 10:17 UTC, sergey-oreshkin commented on src/main/java/com/home/tipster/tips/model/TipDto.java
> +    private Long theme;
тема тоже должна быть @NotNull
в савгере там тема это объект с полем id, но можно и так оставить, я фронт переделаю тогда под такой формат

2022-11-26 10:17 UTC, sergey-oreshkin commented on src/main/java/com/home/tipster/tips/service/TipServiceImpl.java
> +        getTipOrThrow(tip.getTheme().getId());
здесь хочешь по айди темы найти тип?
кстати че то я упустил момент, что тема валидируется когда мы из дто мапим в энтити, так что тут это делать не обязательно

2022-11-26 10:17 UTC, sergey-oreshkin commented on src/main/java/com/home/tipster/tips/service/TipServiceImpl.java
> +        return tipRepository.findAllByThemeId(themeId);
возможно и здесь не обязательно проверять что темы нет, если ее нет - вернется просто пустой список
но если ты хочешь сообщать об этой ошибке наружу, то ок, можно оставить

2022-11-26 10:17 UTC, sergey-oreshkin commented on tipster-api-spec.yml
> +          type: object
вот тут тогда надо поменять что это тип int64 чтоб с твоим кодом совпадало

2022-11-29 11:17 UTC, aBoyarov commented on src/main/java/com/home/tipster/tips/model/Tip.java
> +@ToString
Убрал

2022-11-29 11:17 UTC, aBoyarov commented on src/main/java/com/home/tipster/tips/model/TipDto.java
> +    private Long theme;
Добавил)

2022-11-29 11:18 UTC, aBoyarov commented on src/main/java/com/home/tipster/tips/service/TipServiceImpl.java
> +        getTipOrThrow(tip.getTheme().getId());
Не тот метод потянул, переделал

2022-11-29 11:21 UTC, aBoyarov commented on src/main/java/com/home/tipster/tips/service/TipServiceImpl.java
> +        return tipRepository.findAllByThemeId(themeId);
Согласен, лучше убрать

2022-11-29 14:35 UTC, sergey-oreshkin approved these changes

2022-11-29 14:37 UTC, merged