Themes
sergey-oreshkin/tipster-server pull request #6
Opened 2022-11-27 10:05 UTC by IrinaSlipchenko

2022-11-27 13:20 UTC, sergey-oreshkin requested changes

2022-11-27 13:20 UTC, sergey-oreshkin commented on src/main/java/com/home/tipster/themes/controller/ThemesController.java
> +    private final ThemesServiceImpl themesService;
лучше инжектить через интерфейс

2022-11-27 13:20 UTC, sergey-oreshkin commented on src/main/java/com/home/tipster/themes/model/Themes.java
> +    Long id;
private нужно тут добавить

2022-11-27 13:20 UTC, sergey-oreshkin commented on src/main/java/com/home/tipster/themes/model/Themes.java
> +
Андрей у себя начал на каждое поле писать @Column(name=...) и мне показалось это хорошая практика, может быть будем придерживаться ее, даже если названия совпадают это не всегда очевидно, и так удобнее не надо лазить в базу если вдруг потребуется руками запрос написать

2022-11-27 13:20 UTC, sergey-oreshkin commented on src/main/java/com/home/tipster/themes/model/Themes.java
> +    }
давай не будем нагружать модель посторонней логикой. напиши отдельно класс имплементирующий Comparator и подставляй там где нужна сортировка. что то вроде ThemeTitleComparator

2022-11-27 13:20 UTC, sergey-oreshkin commented on src/main/java/com/home/tipster/themes/service/ThemesServiceImpl.java
> +            log.info("Error, title not unique - {}", themes.getTitle());
давай логировать ошибки будем в @RestControllerAdvice, так это будет более централизованно и никто уже случайно не забудет залогировать

2022-11-27 13:20 UTC, sergey-oreshkin commented on src/main/java/com/home/tipster/themes/dto/ThemesDto.java
> +public class ThemesDto {
давай названия давать в единственном числе если это не коллекции - ThemeDto

2022-11-27 13:20 UTC, sergey-oreshkin commented on src/main/java/com/home/tipster/themes/service/ThemesServiceImpl.java
> +                .sorted()
тут можно sorted(Comparator.comparing(Themes::getTitle)) тут же просто String сравнивается, и только тут это нужно, так что в модели я бы не стал имплементить Comparable

2022-11-27 13:24 UTC, sergey-oreshkin commented on src/main/java/com/home/tipster/themes/service/ThemesServiceImpl.java
> +            log.info("Error, title not unique - {}", themes.getTitle());
и еще, давай такие ошибки логировать уровнем warning, info будет для логов типа как в контроллере

2022-11-28 09:10 UTC, IrinaSlipchenko commented on src/main/java/com/home/tipster/themes/model/Themes.java
> +
ok

2022-11-28 09:16 UTC, IrinaSlipchenko commented on src/main/java/com/home/tipster/themes/service/ThemesServiceImpl.java
> +                .sorted()
ok

2022-11-28 11:00 UTC, sergey-oreshkin approved these changes
хорошо, принимаю

2022-11-28 11:02 UTC, merged